version: 0.0
os: linux
file:
  - source: /app/index.html
    destination: /var/www/html
  - source: source
    destination: /var/www/html/AppTestCodeDeploy
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 180
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 180
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 120
